version: '3.8'
services:

  web:
    image: standobrev/hairsaloon
    build: .
    command: sh -c "python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 HairSaloon.wsgi:application"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    image: nginx
    ports:
      - "81:80" # 81 on local machine, 80 inside the docker container
      - "443:443"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./static_collected:/usr/share/nginx/html/static"
    depends_on:
      - web
    env_file:
      - .env


  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  celery:
    build: .
    command: celery -A HairSaloon worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data: