version: '3'
services:


  celery:
    build: .
    command: celery -A HairSaloon worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025