version: '3.8'
services:

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/collect_static
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: db
    command: sh -c "python manage.py migrate &&
             gunicorn --bind=0.0.0.0:8000 HairSaloon.wsgi:application"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/collect_static
      - media_volume:/app/media
    links:
      - web

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env

  celery:
    build: .
    command: celery -A HairSaloon worker --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data:
  static_volume:
  media_volume: