# Generated by Django 5.0.3 on 2024-03-24 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HairDresser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.TextField(max_length=500)),
                ('working_since', models.DateField()),
                ('services', models.ManyToManyField(related_name='hairdressers', to='services.service')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hairdresser_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
