# Generated by Django 5.0.3 on 2024-03-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairdressers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairdresser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hairdresser',
            name='gender',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='hairdresser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='hairderssers/'),
        ),
        migrations.AddField(
            model_name='hairdresser',
            name='working_since',
            field=models.DateField(blank=True, null=True),
        ),
    ]
