# Generated by Django 5.0.3 on 2024-03-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairdressers', '0002_hairdresser_age_hairdresser_gender_hairdresser_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairdresser',
            name='gender',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
