# Generated by Django 5.0.3 on 2024-03-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairdressers', '0003_alter_hairdresser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairdresser',
            name='age',
        ),
        migrations.AddField(
            model_name='hairdresser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
