# Generated by Django 5.0.3 on 2024-03-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairdressers', '0004_remove_hairdresser_age_hairdresser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairdresser',
            name='background',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hairdresser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='hairdressers/'),
        ),
    ]
