# Generated by Django 5.0.3 on 2024-03-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairdressers', '0005_hairdresser_background_alter_hairdresser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairdresser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=6, null=True),
        ),
    ]
