# Generated by Django 5.0.3 on 2024-03-24 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairdressers', '0006_alter_hairdresser_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hairdresser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hairdresser_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
