# Generated by Django 5.0.3 on 2024-04-09 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import HairSaloon.common.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title',
                 models.CharField(max_length=100, validators=[HairSaloon.common.validators.MinLengthValidator(10)])),
                ('text',
                 models.TextField(max_length=500, validators=[HairSaloon.common.validators.MinLengthValidator(25)])),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments',
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
