# Generated by Django 5.0.3 on 2024-04-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0002_rename_text_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
