# Generated by Django 5.0.3 on 2024-04-14 08:52

import HairSaloon.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_comment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=500, validators=[HairSaloon.common.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(max_length=100, validators=[HairSaloon.common.validators.MinLengthValidator(5)]),
        ),
    ]
