# Generated by Django 5.0.3 on 2024-04-14 09:02

import HairSaloon.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_comment_content_alter_comment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(error_messages={'MinLengthValidator': 'Comment is too short. Min length is 10'}, max_length=500, validators=[HairSaloon.common.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(error_messages={'MinLengthValidator': 'Title is too short. Min length is 5'}, max_length=100, validators=[HairSaloon.common.validators.MinLengthValidator(5)]),
        ),
    ]
