# Generated by Django 5.0.3 on 2024-03-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('male_female_child', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('child', 'child')], max_length=6)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('haircut_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('haircut_photo', models.ImageField(blank=True, null=True, upload_to='haircut_images/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
