# Generated by Django 5.0.3 on 2024-03-24 19:54

import HairSaloon.bookings.models
import HairSaloon.bookings.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hairdressers', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start', models.TimeField(validators=[HairSaloon.bookings.validators.open_hour_validator, HairSaloon.bookings.validators.close_hour_validator])),
                ('end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user_notified', models.BooleanField(default=False)),
                ('hairdresser_notified', models.BooleanField(default=False)),
                ('pre_photo', models.ImageField(blank=True, upload_to=HairSaloon.bookings.models.bookings_directory_path)),
                ('post_photo', models.ImageField(blank=True, upload_to=HairSaloon.bookings.models.bookings_directory_path)),
                ('hairdresser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hairdressers.hairdresser')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-start'],
            },
        ),
    ]
