# Generated by Django 5.0.3 on 2024-03-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-date', '-start']},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='time',
            new_name='start',
        ),
        migrations.AddField(
            model_name='booking',
            name='end',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
