# Generated by Django 5.0.3 on 2024-03-19 21:26

import HairSaloon.bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_options_rename_time_booking_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='post_photo',
            field=models.ImageField(blank=True, upload_to=HairSaloon.bookings.models.bookings_directory_path),
        ),
        migrations.AddField(
            model_name='booking',
            name='pre_photo',
            field=models.ImageField(blank=True, upload_to=HairSaloon.bookings.models.bookings_directory_path),
        ),
    ]
