# Generated by Django 5.0.3 on 2024-03-26 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bookings', '0002_booking_cancelled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='hairdresser_notified',
            new_name='initial_hairdresser_notified',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='user_notified',
            new_name='initial_user_notified',
        ),
    ]
