# Generated by Django 5.0.3 on 2024-03-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_hairdresser_notified_booking_initial_hairdresser_notified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='alter_hairdresser_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='alter_user_notified',
            field=models.BooleanField(default=False),
        ),
    ]
