# Generated by Django 5.0.3 on 2024-03-20 22:17

import HairSaloon.bookings.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_post_photo_booking_pre_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='start',
            field=models.TimeField(validators=[HairSaloon.bookings.validators.open_hour_validator, HairSaloon.bookings.validators.close_hour_validator]),
        ),
    ]
