# Generated by Django 5.0.3 on 2024-03-26 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_alter_hairdresser_notified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pending',
        ),
    ]
