# Generated by Django 5.0.3 on 2024-04-10 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_booking_completed_remove_booking_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='alter_hairdresser_notified',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='alter_user_notified',
        ),
    ]
