# Generated by Django 5.0.3 on 2024-04-14 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_remove_booking_alter_hairdresser_notified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='post_photo',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pre_photo',
        ),
    ]
